### ISSUE TITLE
Importing unix_connect from rpyc.utils.classic

### ISSUE THREAD

**Issue by danikdanik** [alonho/pystuck#7]
rpyc 3.3 doesn't contain the unix_connect function and thus the import fails.

**Comment by tgoodlet** [comment]
To extend this, is there any reason to stay on `'rpyc == 3.2.3'`?
I guess an api dependency?

**Comment by alonho** [comment]
It's possible the latest Rpyc can work. Simply requires testing.

**Comment by tgoodlet** [comment]
@alonho got it working after stripping out the `unix_socket` stuff which is gone from upstream `rpyc`. I'm putting up a PR in a few minutes.
